const WORDS = [
  'ABOUT','ABUSE','ACTOR','ACUTE','ADMIT','ADOPT','ADULT','AFTER','AGAIN','AGENT',
  'AGREE','AHEAD','ALARM','ALBUM','ALERT','ALIKE','ALIGN','ALIVE','ALLAY','ALLEY',
  'ALLOW','ALONE','ALONG','ALTER','AMBER','ANGEL','ANGER','ANGLE','ANGRY','ANKLE',
  'ANNEX','ANTIC','APART','APPLE','APPLY','ARENA','ARGUE','ARISE','ARMOR','AROSE',
  'ARRAY','ARROW','ASIDE','ASSET','ATLAS','ATTIC','AUDIO','AUDIT','AVOID','AWAKE',
  'AWARD','AWARE','AWFUL','BASIC','BASIS','BATCH','BEACH','BEGAN','BEGIN','BEING',
  'BELOW','BENCH','BERRY','BILLS','BIRTH','BLACK','BLADE','BLAME','BLAND','BLAST',
  'BLAZE','BLEED','BLEND','BLESS','BLIND','BLOCK','BLOOD','BLOWN','BLUES','BLUNT',
  'BOARD','BOOST','BOOTH','BOUND','BOXER','BRAIN','BRAND','BRAVE','BREAD','BREAK',
  'BREED','BRICK','BRIDE','BRIEF','BRING','BROKE','BROOK','BROWN','BRUSH','BUDDY',
  'BUILD','BUILT','BUNCH','BURST','BUYER','CABLE','CAMEL','CARGO','CARRY','CATCH',
  'CAUSE','CHAIN','CHAIR','CHAOS','CHARM','CHART','CHASE','CHEAP','CHECK','CHEEK',
  'CHESS','CHEST','CHIEF','CHILD','CHOIR','CIVIC','CIVIL','CLAIM','CLASS','CLEAN',
  'CLEAR','CLERK','CLICK','CLIFF','CLIMB','CLING','CLOCK','CLONE','CLOSE','CLOTH',
  'CLOUD','COACH','COAST','COLOR','COMIC','CORAL','COUNT','COURT','COVER','CRAFT',
  'CRANE','CRASH','CRAZY','CREEK','CRIME','CRISP','CROSS','CROWD','CROWN','CRUEL',
  'CRUSH','CURVE','CYCLE','DAILY','DANCE','DEATH','DEBUT','DELAY','DELTA','DENSE',
  'DEPOT','DEPTH','DERBY','DIGIT','DINER','DIRTY','DISCO','DIZZY','DONOR','DOUBT',
  'DOUGH','DRAFT','DRAMA','DRANK','DRAPE','DREAM','DRESS','DRIFT','DRINK','DRIVE',
  'DROVE','DRUNK','DRYER','DWARF','DYING','EAGER','EAGLE','EARLY','EARTH','EIGHT',
  'ELITE','EMPTY','ENEMY','ENJOY','ENTER','EQUAL','ERROR','EVENT','EVERY','EXACT',
  'EXIST','EXTRA','FABLE','FANCY','FAINT','FAIRY','FAITH','FALSE','FAVOR','FEAST',
  'FERRY','FEVER','FIBER','FIELD','FIFTY','FIGHT','FINAL','FIRST','FIXED','FLAKE',
  'FLAME','FLASK','FLESH','FLIES','FLOAT','FLOOD','FLOOR','FLORA','FLOUR','FLUID',
  'FOCUS','FORGE','FORTH','FOUND','FRAME','FRANK','FREED','FRESH','FRONT','FROST',
  'FROZE','FRUIT','FUNNY','GAMUT','GAUGE','GHOST','GIVEN','GLASS','GLOOM','GLORY',
  'GLOSS','GLOVE','GOING','GRACE','GRADE','GRAIN','GRAND','GRANT','GRAPH','GRASP',
  'GRASS','GRAVE','GREAT','GREED','GREEN','GREET','GRIEF','GRIND','GROAN','GROUP',
  'GROVE','GROWN','GUARD','GUESS','GUIDE','GUILD','GUSTO','HAPPY','HARSH','HATCH',
  'HAVEN','HEART','HEAVY','HEDGE','HENCE','HERBS','HINGE','HONEY','HONOR','HORSE',
  'HOTEL','HOURS','HOUSE','HUMAN','HUMOR','HYPER','IDEAL','IMAGE','IMPLY','INDEX',
  'INFER','INPUT','INTER','INTRO','ISSUE','IVORY','JEWEL','JUDGE','JUICE','JUICY',
  'KARMA','KNIFE','KNOCK','KNOWN','LABEL','LANCE','LARGE','LASER','LATER','LAUGH',
  'LAYER','LEARN','LEASE','LEAST','LEAVE','LEGAL','LEMON','LEVEL','LIGHT','LIMIT',
  'LINEN','LINER','LOCAL','LODGE','LOGIC','LOOSE','LOVER','LOWER','LOYAL','LUCKY',
  'LUNAR','LYING','MAGIC','MAJOR','MAKER','MANOR','MARCH','MARSH','MATCH','MAYOR',
  'MEDIA','MERCY','MERGE','MERIT','METAL','MIGHT','MINOR','MINUS','MIXED','MODEL',
  'MONEY','MONTH','MORAL','MOTOR','MOUNT','MOUSE','MOVED','MOVIE','MUSIC','NAIVE',
  'NEVER','NIGHT','NOBLE','NOISE','NORTH','NOTED','NOVEL','NURSE','NYMPH','OCCUR',
  'OCEAN','OFFER','OFTEN','ONION','OPERA','ORDER','OTHER','OUGHT','OUTER','OWNER',
  'OXIDE','OZONE','PAINT','PANEL','PAPER','PARTY','PASTA','PATCH','PAUSE','PEACE',
  'PEARL','PEDAL','PENNY','PHASE','PHONE','PHOTO','PIANO','PIECE','PILOT','PITCH',
  'PIXEL','PIZZA','PLACE','PLAIN','PLANE','PLANT','PLATE','PLAZA','PLUCK','PLUMB',
  'PLUME','POINT','POLAR','POPPY','PORCH','POWER','PRESS','PRICE','PRIDE','PRIME',
  'PRIOR','PRIZE','PROBE','PROSE','PROVE','PROXY','PULSE','PUNCH','PUPIL','PURSE',
  'QUEEN','QUERY','QUEST','QUEUE','QUICK','QUIET','QUOTA','QUOTE','RADAR','RADIO',
  'RAISE','RALLY','RANGE','RAPID','RATIO','REACH','READY','REALM','REBEL','REFER',
  'REIGN','RELAY','REMIX','RENEW','REPAY','REPLY','RIDER','RIDGE','RIGHT','RIGID',
  'RISKY','RIVER','RIVAL','RIVET','ROBOT','ROCKY','ROUGE','ROUGH','ROUND','ROUTE',
  'ROYAL','RULER','RURAL','SADLY','SAINT','SALAD','SAUCE','SCALE','SCARY','SCENE',
  'SCOPE','SCORE','SCOUT','SEDAN','SEIZE','SENSE','SERVE','SETUP','SEVEN','SHADE',
  'SHAKE','SHALL','SHAME','SHAPE','SHARE','SHARP','SHEER','SHIFT','SHIRT','SHOCK',
  'SHOOT','SHORE','SHORT','SHOUT','SIGHT','SINCE','SIXTH','SIXTY','SKILL','SLATE',
  'SLAVE','SLEEP','SLICE','SLIDE','SMALL','SMART','SMILE','SMOKE','SOLAR','SOLID',
  'SOLVE','SORRY','SOUND','SOUTH','SPACE','SPARE','SPARK','SPAWN','SPEAK','SPEAR',
  'SPEED','SPEND','SPICE','SPIKE','SPINE','SPLIT','SPOKE','SPORT','SPRAY','SQUAD',
  'STACK','STAGE','STAIN','STAIR','STAKE','STALE','STAMP','STAND','STARE','START',
  'STATE','STEAM','STEEL','STEEP','STEER','STERN','STICK','STILL','STING','STOCK',
  'STONE','STOOD','STORE','STORM','STORY','STOVE','STRAP','STRAW','STRIP','STUCK',
  'STUDY','STYLE','SUGAR','SUITE','SUPER','SURGE','SWAMP','SWEAR','SWEEP','SWEET',
  'SWEPT','SWIFT','SWIRL','SWOOP','SWORD','SWORN','TABLE','TABOO','TAKEN','TASTE',
  'TEACH','TENSE','TENTH','THEIR','THEME','THERE','THESE','THICK','THING','THINK',
  'THIRD','THOSE','THREE','THREW','THROW','TIGER','TIGHT','TIRED','TITLE','TODAY',
  'TOKEN','TOUCH','TOUGH','TOWER','TOXIC','TRACK','TRADE','TRAIL','TRAIN','TRAIT',
  'TRASH','TREAT','TREND','TRIAL','TRICK','TRIED','TROOP','TRUCK','TRULY','TRUST',
  'TRUTH','TUMOR','TUNER','TWIRL','TWIST','ULTRA','UNDER','UNIFY','UNION','UNITE',
  'UNITY','UNTIL','UPPER','UPSET','URBAN','USAGE','USING','USUAL','UTTER','VALID',
  'VALUE','VAPOR','VAULT','VERSE','VIDEO','VIGOR','VIRAL','VIRUS','VISIT','VISTA',
  'VITAL','VIVID','VOCAL','VOICE','VOTER','WASTE','WATCH','WATER','WEIGH','WEIRD',
  'WHEAT','WHEEL','WHERE','WHILE','WHITE','WHOLE','WHOSE','WIDER','WITTY','WOMAN',
  'WOMEN','WORLD','WORRY','WORSE','WORST','WORTH','WOULD','WOUND','WRATH','WRITE',
  'WRONG','YACHT','YIELD','YOUNG','YOUTH','ZEBRA','ABBOT','ADEPT','AFOOT','ALOFT',
  'ANNOY','ARDOR','ARMOR','AROMA','ATONE','AXIOM','BADGE','BRAWL','BRISK','BUDGE',
  'BULGE','BULLY','BURLY','CABIN','CATCH','CELLO','CHIME','CHIMP','CHIVE','CHOMP',
  'CLAMP','CLASP','CAULK','CEDAR','CHANT','CHEWY','CHOIR','CLANK','CLASH','CLEFT',
  'CLUMP','COLON','COMMA','CORPS','COVET','CRIMP','CROAK','CRUMB','CRYPT','CUBIC',
  'CURLY','CUTIE','DAISY','DECOY','DEITY','DELVE','DEMON','DENSE','DEPOT','DERBY',
  'DECAL','DIDNT','DISCO','DITTO','DITTY','DODGE','DOGMA','DOMED','DONOR','DOPEY',
  'DOWDY','DOWEL','DOWRY','DRONE','DROOL','DROOP','DROVE','EPOCH','ETHOS','EVADE',
  'EXPEL','EXPUNGE','FABLE','FARCE','FATAL','FEIGN','FELON','FERAL','FETID','FIEND',
  'FIERY','FIFTH','FISHY','FLAIL','FLAIR','FLANK','FLARE','FLOSS','FLUKE','FOAMY',
  'FOLIO','FOLLY','FORAY','FROND','FOYER','FRAIL','FREAK','FROTH','FROZE','FROZE',
  'GAMER','GAVEL','GIDDY','GIRTH','GLARE','GLIDE','GLINT','GLOAT','GLUED','GLYPH',
  'GNASH','GORGE','GOUGE','GRAFT','GRAZE','GRIPE','GRIMY','GROVE','GRUFF','GUILE',
  'GUISE','GULCH','GUMMY','GUPPY','HIPPO','HOMER','HORDE','HUMPH','HUSKY','HYDRA',
  'IBIS','ICING','IDIOM','IDIOT','INANE','INBOX','INCUR','INDIE','INEPT','INERT',
  'INFIX','INGOT','INLAY','INLET','IRATE','IRONY','ITCHY','JAZZY','JERKY','JINGO',
  'JIVES','JOBBY','JOLLY','JOUST','KAZOO','KINKY','KIOSK','KITTY','KNACK','KNEEL',
  'KNELT','KNOLL','KOOKY','LAPEL','LAPSE','LARVA','LATENT','LEDGE','LEECH','LEERY',
  'LEFTY','LEMUR','LIBEL','LIEGE','LINER','LIVID','LLAMA','LOATH','LOFTY','LUSTY',
  'MADLY','MAIZE','MAXIM','MELEE','MELON','METRO','MILKY','MIRTH','MISER','MOTTO',
  'MOULT','MUCKY','MUDDY','MUGGY','MURKY','MUTED','NADIR','NASTY','NERDY','NIPPY',
  'NOBLE','NUTTY','OAKUM','ODDLY','OFFAL','OLIVE','OMBRE','ONSET','OPTIC','OVARY',
  'OVINE','OVOID','PADDY','PAGAN','PANSY','PATSY','PAVED','PEEVE','PEPPY','PERCH',
  'PERIL','PERKY','PETTY','PINCH','PINEY','PIPIT','PITHY','PLAID','PLAIT','PLUMB',
  'PLUNK','POACH','PODGY','POGROM','POTTY','POUTY','PROWL','PRUDE','PSALM','PSYCH',
  'PUDGY','PUFFY','PYGMY','QUAFF','QUALM','QUASH','QUIRK','QUOTA','RASPY','RATTY',
  'REBUS','RECAP','RECUT','REDUX','REEDY','REGAL','REPEL','REPLETE','RERUN','RETRO',
  'REVEL','REVUE','RIGOR','RIPER','RITZY','ROWDY','RUDDY','RUGBY','RUPEE','RUSTY',
  'SADLY','SAGGY','SALVO','SASSY','SATAY','SATIN','SAVVY','SEEDY','SERUM','SHAKY',
  'SHALE','SHANK','SHEEP','SHEEN','SHREW','SHIRK','SHOAL','SHOWY','SIMMER','SINEW',
  'SISSY','SITAR','SKATE','SKIMP','SKIPPER','SKIRT','SKULK','SKUNK','SLIMY','SLUNG',
  'SLUNK','SLURP','SLUSH','SLYLY','SNACK','SNAKY','SNARE','SNEER','SNIDE','SNIFF',
  'SNORE','SNORT','SNOUT','SOGGY','SOOTH','SPASM','SPECK','SPOOK','SPORE','SPOUT',
  'SPUNK','STARK','STEIN','STOIC','STOKE','STOMP','STONY','STOOGE','STORK','STOUT',
  'STRUT','STUMP','STUNG','STUNK','STUNT','SUAVE','SUNNY','SURLY','SWATH','SWIPE',
  'SWOON','SYLPH','SYRUP','TAWNY','TACKY','TAFFY','TALON','TANGO','TAPER','TARDY',
  'TAUNT','TAWNY','TEPID','TERSE','THYME','TIARA','TIBIA','TILTED','TIPSY','TITAN',
  'TITHE','TOFFY','TOPAZ','TORSO','TOTEM','TOUCAN','TOXIC','TRUCE','TRULY','TRUMP',
  'TRYST','TULIP','TULLE','TUMMY','TUNIC','TUQUE','TURBO','TUTOR','TWEED','TWERP',
  'TYPED','TYPIC','ULCER','ULTRA','UNCUT','UNDID','UNFED','UNFIT','UNGRATEFUL',
  'UNLIT','UNMET','UNPIN','UNSET','UNWED','UNWRAP','USHER','VAGUE','VALET','VAPID',
  'VAUNT','VENOM','VERGE','VEXED','VIGIL','VINYL','VIPER','VISOR','VIXEN','VODKA',
  'WACKY','WAGER','WALTZ','WARTY','WAXEN','WEEDY','WHACK','WHALE','WHIFF',
  'WHIRL','WISPY','WITTY','WOOZY','WRATH','WRING','WROTE','YEARN','ZESTY',
  // OO words
  'BROOM','BLOOM','BROOD','STOOL','STOOP','PROOF','SPOON','SCOOP','CROOK','SHOOK',
  'DROOL','DROOP','TROOP','GROOL','GROOM','SNOOP','VROOM','SPOOL','STOOP','SWOOP',
  'TABOO','IGLOO','WHOOP','TROOP','SPOOF','STOOD','BLOOD','FLOOD','FLOOR','BROOK',
  'CROON','DROOL','SWOON','SPOOK','STOOL','TROOP','SMOKY',
  // EE words
  'SHEET','CREEP','KNEEL','SLEEK','CHEEK','CREEK','GEESE','FLEECE','STEEP','STEEL',
  'SPEED','GREED','FREED','BREED','BLEED','TREED','CREED','TWEED','BREED','SNEER',
  'SHEER','STEER','GREET','SWEET','FLEET','SLEET','SHEET','TWEET','WHEEL','QUEEN',
  'GREEN','SCENE','SERENE','THESE',
  // LL words
  'BELLE','IELLE','SPELL','SMELL','SHELL','SHELF','SWILL','SPILL','SKILL','THRILL',
  'GRILL','TRILL','FRILL','KNOLL','STALL','SMALL','STALL','SHALL','SCALL','SHAWL',
  'CRAWL','DRAWL','PROWL','GROWL','SCOWL','TRAWL','SWELL','DWELL','SPELL','KNELL',
  'QUELL','EXPEL','LAPEL','REPEL','NOVEL','LEVEL','JEWEL','TOWEL','VOWEL','BOWEL',
  'PIXEL','ANGEL','EXCEL','FUNNEL','PANEL','CAMEL',
  // Common everyday words
  'ANKLE','ATTIC','BENCH','BLAZE','BLEND','BLISS','BLOAT','BLOOM','BLOWN','BONUS',
  'BOOTH','BOXER','BRAWL','BRAWN','BRISK','BROTH','BUDGE','BULGE','BULLY','BUMPY',
  'BURLY','CABIN','CANDY','CATCH','CEDAR','CHANT','CHICK','CHIME','CHIMP','CHIVE',
  'CHOCK','CHOMP','CHORD','CIVIC','CLAMP','CLANG','CLANK','CLASH','CLASP','CLEFT',
  'CLUMP','COBRA','COLON','COMMA','CONCH','CORAL','CORNY','CORPS','COVET','CRAMP',
  'CRIMP','CRISP','CROAK','CRUMB','CUBIC','CURLY','DAISY','DECOY','DEITY','DELVE',
  'DENSE','DEPOT','DERBY','DIGIT','DISCO','DODGE','DOGMA','DOPEY','DOWEL','DOWRY',
  'DRONE','EPOCH','ETHOS','EVADE','FARCE','FATAL','FEIGN','FELON','FERAL','FETID',
  'FIEND','FIERY','FISHY','FLAIL','FLAIR','FLANK','FLARE','FLOSS','FLUKE','FOAMY',
  'FOLIO','FOLLY','FORAY','FOYER','FRAIL','FROND','FROTH','GAVEL','GIDDY','GIRTH',
  'GLARE','GLIDE','GLINT','GLOAT','GORGE','GOUGE','GRAFT','GRAZE','GRIMY','GRIPE',
  'GRUFF','GULCH','GUMMY','HIPPO','HORDE','HUSKY','ICING','IDIOM','IDIOT','INANE',
  'INCUR','INEPT','INERT','INGOT','IRATE','ITCHY','JAZZY','JERKY','JOLLY','JOUST',
  'KAZOO','KINKY','KIOSK','KITTY','KNACK','KNELT','KOOKY','LAPEL','LAPSE','LARVA',
  'LEDGE','LEECH','LEERY','LEMUR','LIBEL','LIVID','LOATH','LOFTY','LUSTY','MADLY',
  'MAIZE','MAXIM','MELEE','MELON','METRO','MILKY','MIRTH','MISER','MOTTO','MUCKY',
  'MUDDY','MUGGY','MURKY','NADIR','NASTY','NERDY','NUTTY','ODDLY','OLIVE','ONSET',
  'PADDY','PAGAN','PANSY','PATSY','PEEVE','PERCH','PERIL','PERKY','PETTY','PINCH',
  'PITHY','PLAID','PLAIT','PLUNK','POACH','POTTY','PRUDE','PUDGY','PUFFY','PYGMY',
  'QUAFF','QUALM','QUASH','QUIRK','RASPY','RATTY','REBUS','REEDY','REGAL','RETRO',
  'REVEL','RIGOR','RITZY','ROWDY','RUDDY','RUGBY','RUPEE','RUSTY','SAGGY','SALVO',
  'SASSY','SATAY','SATIN','SAVVY','SEEDY','SERUM','SHAKY','SHALE','SHANK','SHEEN',
  'SHREW','SHIRK','SHOAL','SHOWY','SINEW','SISSY','SITAR','SKATE','SKIMP','SKULK',
  'SKUNK','SLIMY','SLURP','SLUSH','SNAKY','SNARE','SNIDE','SNIFF','SNORE','SNORT',
  'SNOUT','SOGGY','SPASM','SPECK','SPORE','SPOUT','SPUNK','STARK','STOIC','STOKE',
  'STOMP','STONY','STORK','STOUT','STRUT','STUMP','STUNG','STUNK','STUNT','SUAVE',
  'SURLY','SWATH','SWIPE','SYLPH','SYRUP','TACKY','TAFFY','TALON','TANGO','TAPER',
  'TARDY','TAUNT','TAWNY','TEPID','TERSE','THYME','TIARA','TIPSY','TITAN','TITHE',
  'TOPAZ','TORSO','TOTEM','TRUCE','TRYST','TULIP','TUMMY','TUNIC','TURBO','TUTOR',
  'TYPED','ULCER','UNCUT','UNDID','UNFIT','UNLIT','USHER','VAGUE','VALET','VAPID',
  'VAUNT','VENOM','VERGE','VEXED','VIGIL','VINYL','VIPER','VISOR','VIXEN','VODKA',
  'SWOOP',
  // More common words likely to be guessed
  'ABBEY','ABHOR','ABIDE','ABYSS','ADORN','AFOUL','AFTER','AGILE','AGLOW','AGONY',
  'AGORA','AISLE','ALGAE','ALIBI','ALOOF','ALOUD','ALUM','AMAZE','AMBLE','AMEND',
  'AMISS','AMUSE','ANNOY','ANTIC','ARDOR','AROMA','ATONE','ATOP','AVAIL','AVID',
  'AWAIT','AWASH','AWFUL','BABBLE','BADLY','BAGEL','BAKED','BALER','BASTE','BATCH',
  'BATON','BAYOU','BEARD','BEAST','BEECH','BEFIT','BELIE','BELLE','BERET','BESET',
  'BEVEL','BEWITCH','BIDDY','BIGHT','BIGOT','BIKER','BILLY','BINGE','BIRCH','BLADE',
  'BLEAT','BLIMP','BLINK','BLOAT','BLOKE','BOOZE','BORAX','BOTCH','BOUGH','BRAID',
  'BRAKE','BRIBE','BRINK','BROIL','BROOD','BROOK','BRUNT','BULKY','BUMBLE','BUNCH',
  'BUNNY','BRAID','CEDAR','CHAFE','CHALK','CHAMP','CHAOS','CHASM','CHEAT','CHEEP',
  'CHESS','CHEST','CHIDE','CHILE','CHINK','CHORE','CHUCK','CHURN','CINCH','CLACK',
  'CLAD','CLEAT','CLERK','CLICK','CLINK','CLIP','CLOAK','CLOCK','CLOGS','CLOUT',
  'COALS','COATS','COBIA','COILS','COOKY','CREAK','CREEK','CREPT','CREST','CROPS',
  'CROWD','CRUEL','CRUMB','CRYPT','CUNNY','CUSHY','DADDY','DAUNT','DECAL','DECRY',
  'DELTA','DEMUR','DEPOT','DERBY','DETER','DETOX','DHOW','DIGIT','DIMLY','DINGO',
  'DITTY','DIVAN','DIVER','DIVVY','DIZZY','DODGY','DOMLY','DOWDY','DRANK','DRAPE',
  'DRAWN','DREAD','DREGS','DROIT','DUKES','DUVET','DWELT','EARLY','EASEL','EDICT',
  'EIGHT','ELBOW','EMBER','EMOTE','EMPTY','ENACT','ENDOW','ENEMA','ENSUE','ENVOY',
  'EPOXY','EPOCH','ERODE','ERUPT','ETUDE','EVOKE','EXERT','EXILE','EXPEL','EXTOL',
  'FABLE','FACET','FAGOT','FAKIR','FARCE','FATED','FAUNA','FEIGN','FENCE','FERAL',
  'FIERY','FIFTY','FIXER','FJORD','FLAIR','FLASH','FLAWY','FLECK','FLESH','FLIRT',
  'FLOSS','FLOUT','FLUME','FLUTE','FOLLY','FORGE','FORTE','FOUND','FREAK','FRESH',
  'FROCK','FROZE','FRUGAL','FUNGI','GAUZE','GECKO','GENIE','GENRE','GIVEN','GLEAM',
  'GLEAN','GLOOM','GLOSS','GLOVE','GLYPH','GOLLY','GORSE','GOURD','GRAZE','GREET',
  'GROAN','GROIN','GROPE','GROUT','GRUEL','GRUFF','GUILE','GUISE','GUSTO','HAVOC',
  'HAZEL','HEAVY','HEDGE','HELIX','HERTZ','HIGHS','HOIST','HOITY','HOMER','HOPPY',
  'HUNKY','HYPNO','IGLOO','INEPT','INFER','INLAY','INNER','INPUT','INTER','INTRO',
  'JAUNT','JOUST','KARST','KNAVE','KNOCK','KUDOS','LANCE','LATCH','LATHE','LEACH',
  'LEAFY','LEAKY','LEDGE','LIBEL','LINER','LITHE','LIVER','LIVID','LLAMA','LOCAL',
  'LOCKS','LODGE','LOONY','LOWLY','LUCID','LUNGE','LUSTY','MACHO','MANGY','MAPLE',
  'MARSH','MASSE','MATCH','MAXIM','MEALY','MEATY','MELON','MERCY','MESSY','METAL',
  'MIRTH','MISER','MISTY','MITRE','MIXED','MOODY','MORPH','MOSSY','MOUSY','MUCKY',
  'MUDDY','MUGGY','MULCH','MUSTY','MYRRH','NADIR','NASTY','NEEDY','NIECE','NIFTY',
  'NINNY','NIPPY','NOSEY','NUBBY','OAKEN','OFTEN','OLIVE','OOZE','OUTDO','OVOID',
  'OXIDE','OZONE','PATCHY','PATIO','PATSY','PENAL','PERKY','PHONY','PLONK','PLUME',
  'PLUMP','PLUNK','POISE','POLKA','POLYP','POPPY','POUTY','POWER','PRIMA','PRIMO',
  'PRIVY','PRIMP','PRION','PRISM','PRIVY','PRONE','PRONG','PRANK','PSALM','PUBIC',
  'PULSE','PUNCH','PUPIL','PUPPY','PURGE','QUEUE','QUILL','QUIRK','RABBI','RADII',
  'RADON','RAMEN','RANCH','RANGY','RAPID','RAVEL','RAWLY','REIGN','RELAX','RENEW',
  'REPAY','REPEL','RERUN','REUSE','REVEL','RIDER','RIPEN','RIVET','RODEO','ROOMY',
  'ROUGE','ROUGH','ROWDY','ROWEL','RUGBY','RUNNY','RUSTY','SADLY','SATYR','SAUNA',
  'SCALD','SCALP','SCRAM','SCUFF','SEIZE','SERVE','SETUP','SHAFT','SHADY','SHAKE',
  'SHAME','SHAPE','SHARK','SHARP','SHAVE','SHAWL','SHEEN','SHINY','SHOAL','SHORE',
  'SHOUT','SHRUG','SIEGE','SILKY','SKIMP','SKIRT','SKULL','SLAIN','SLANT','SLASH',
  'SLEEK','SLEET','SLEW','SLIME','SLOSH','SLOTH','SLUMP','SLUNG','SLUNK','SLYLY',
  'SMASH','SMEAR','SMELT','SMIRK','SMITE','SMITH','SMOCK','SMOGGY','SMOKY','SNEAK',
  'SNOOT','STOMP','STRAP','STRUM','SUNNY','SUSHI','TABBY','TEACH','TEPID','TERSE',
  'THEFT','THORN','TIARA','TIDAL','TITHE','TONGS','TOTEM','TOPAZ','TOWER','TOXIC',
  'TRICE','TRIPE','TRITE','TROLL','TROTH','TROUT','TRUMP','TRUSS','TUBER','TULIP',
  'TUNER','TUQUE','TWERP','ULTRA','UNFIT','USURP','UTTER','VAGUE','VERSE','VIDEO',
  'VIGIL','VIOLA','VIPER','VIRGO','VISIT','VISTA','VOMIT','VOUCH','VOILA','WALTZ',
  'WATCH','WEEDY','WHELP','WRATH','WRING','WRIST','YACHT','YEARN','ZEBRA',
];

// Filter to exactly 5-letter words and deduplicate
const VALID_WORDS = [...new Set(WORDS.filter(w => w.length === 5))];

function getRandomWord(used = []) {
  const available = VALID_WORDS.filter(w => !used.includes(w));
  const pool = available.length > 0 ? available : VALID_WORDS;
  return pool[Math.floor(Math.random() * pool.length)];
}

function checkGuess(guess, answer) {
  const result = new Array(5).fill('absent');
  const ansArr = answer.split('');
  const guessArr = guess.split('');
  const ansUsed = new Array(5).fill(false);
  const guessUsed = new Array(5).fill(false);

  // Pass 1: exact matches (green)
  for (let i = 0; i < 5; i++) {
    if (guessArr[i] === ansArr[i]) {
      result[i] = 'correct';
      ansUsed[i] = true;
      guessUsed[i] = true;
    }
  }

  // Pass 2: present in wrong position (yellow)
  for (let i = 0; i < 5; i++) {
    if (guessUsed[i]) continue;
    for (let j = 0; j < 5; j++) {
      if (!ansUsed[j] && guessArr[i] === ansArr[j]) {
        result[i] = 'present';
        ansUsed[j] = true;
        break;
      }
    }
  }

  return result;
}

function isValidWord(word) {
  return VALID_WORDS.includes(word.toUpperCase());
}

module.exports = { getRandomWord, checkGuess, isValidWord, VALID_WORDS };
